spring:
  mail:
    default-encoding: UTF-8
    host: smtp.163.com
    protocol: smtp
    username: xxxxxx
    # 服务授权码, 不是邮箱密码
    password: ggggggg
    properties:
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 3000
      mail.smtp.writetimeout: 5000
  freemarker:
    #设置编码格式
    charset: utf-8
    #设置文件后缀
    suffix: .ftl
    #设置ftl文件路径
    template-loader-path: classpath:/templates
    #关闭缓存，及时刷新，上线生产环境需要改为true
    cache: false
  redis:
    host: 192.168.0.156
    port: 6379
  session:
    store-type: redis
    timeout: 30m
    redis:
      # 表示不支持 键空间事件; 默认值是 notify_keyspace_events 表示支持
      # 这里有个问题就是, 如果一开始启用了该功能, 后期想关闭该功能, 仅把此处设置为 none 是不行的, 必须重启 redis, 再讲此处设置为 none.
      # 再研究下, 看是 bug 提个 issue, 还是说 还有其他方案.
      configure-action: none
      cleanup-cron: 0 * * * * * # 清理过期 session 的定时任务
      namespace: spring:session # 前缀
logging:
  file: logs/spring-boot-mail.log
server:
  port: 8081
  servlet:
    session:
      timeout: 30m
      cookie:
        http-only: true
#        domain: zy.com
        path: /
#        secure: true
        name: authId

#spring-boot 端点相关配置
endpoints:
  shutdown:
    enabled: true
  #    关闭所有端点
  enabled: false
  #  只留一个端点
  beans:
    enabled: true
#    定制endpoint的id或者访问路径
#  beans:
#    id: mybean


# 从yml中解析自定义配置
person:
  lastName: 张三
  age: 20
  boss: false
  birth: 1999/09/09
  maps: {k1: v1,k2: v2}
  lists:
    - z1
    - z2
    - z3
  dog:
    name: little dog
    age: 2